import { lazy, type ComponentType } from 'react'

export interface ShowcaseProp {
  id: string
  name: string
  color: string
  component: React.LazyExoticComponent<ComponentType>
}

export interface ShowcaseCategory {
  id: string
  name: string
  icon: string
  props: ShowcaseProp[]
}

function lz(importFn: () => Promise<Record<string, any>>, exportName: string) {
  return lazy(() => importFn().then(m => ({ default: m[exportName] })))
}

export const showcaseCategories: ShowcaseCategory[] = [
  {
    id: 'general', name: 'General', icon: '🎨',
    props: [
      { id: 'ai-brain', name: 'AI Brain', color: '#00ffff', component: lz(() => import('../../props/showcase/AIBrain'), 'AIBrain') },
      { id: 'data-crystal', name: 'Data Crystal', color: '#aa44ff', component: lz(() => import('../../props/showcase/DataCrystal'), 'DataCrystal') },
      { id: 'code-terminal', name: 'Code Terminal', color: '#66ff66', component: lz(() => import('../../props/showcase/CodeTerminal'), 'CodeTerminal') },
      { id: 'coffee-machine', name: 'Coffee Machine', color: '#ff6644', component: lz(() => import('../../props/showcase/CoffeeMachine'), 'CoffeeMachine') },
      { id: 'whiteboard', name: 'Whiteboard', color: '#ffee44', component: lz(() => import('../../props/showcase/Whiteboard'), 'Whiteboard') },
      { id: 'plant', name: 'Plant', color: '#44dd66', component: lz(() => import('../../props/showcase/Plant'), 'Plant') },
      { id: 'server-rack', name: 'Server Rack', color: '#4488ff', component: lz(() => import('../../props/showcase/ServerRack'), 'ServerRack') },
      { id: 'hourglass', name: 'Hourglass', color: '#ffcc44', component: lz(() => import('../../props/showcase/Hourglass'), 'Hourglass') },
      { id: 'globe', name: 'Globe', color: '#44ddff', component: lz(() => import('../../props/showcase/Globe'), 'Globe') },
      { id: 'rocket', name: 'Rocket', color: '#ff4444', component: lz(() => import('../../props/showcase/Rocket'), 'Rocket') },
      { id: 'whiteboard-markers', name: 'Whiteboard Markers', color: '#f0f0f0', component: lz(() => import('../../props/showcase/general/WhiteboardMarkers'), 'WhiteboardMarkers') },
      { id: 'bulletin-board', name: 'Bulletin Board', color: '#cc9955', component: lz(() => import('../../props/showcase/general/BulletinBoard'), 'BulletinBoard') },
      { id: 'trash-can', name: 'Trash Can', color: '#667788', component: lz(() => import('../../props/showcase/general/TrashCan'), 'TrashCan') },
      { id: 'paper-shredder', name: 'Paper Shredder', color: '#ddddee', component: lz(() => import('../../props/showcase/general/PaperShredder'), 'PaperShredder') },
      { id: 'desk-fan', name: 'Desk Fan', color: '#4488dd', component: lz(() => import('../../props/showcase/general/DeskFan'), 'DeskFan') },
      { id: 'air-purifier', name: 'Air Purifier', color: '#44ff88', component: lz(() => import('../../props/showcase/general/AirPurifier'), 'AirPurifier') },
      { id: 'space-heater', name: 'Space Heater', color: '#ff6644', component: lz(() => import('../../props/showcase/general/SpaceHeater'), 'SpaceHeater') },
      { id: 'desk-organizer', name: 'Desk Organizer', color: '#ffcc44', component: lz(() => import('../../props/showcase/general/DeskOrganizerTray'), 'DeskOrganizerTray') },
      { id: 'cable-clips', name: 'Cable Clips', color: '#ff44ff', component: lz(() => import('../../props/showcase/general/CableClips'), 'CableClips') },
      { id: 'picture-frame', name: 'Picture Frame', color: '#aa7744', component: lz(() => import('../../props/showcase/general/PictureFrame'), 'PictureFrame') },
      { id: 'potted-succulent', name: 'Potted Succulent', color: '#66cc88', component: lz(() => import('../../props/showcase/general/PottedSucculent'), 'PottedSucculent') },
      { id: 'desk-mat', name: 'Desk Mat', color: '#334466', component: lz(() => import('../../props/showcase/general/DeskMat'), 'DeskMat') },
      { id: 'coaster', name: 'Coaster', color: '#cc9955', component: lz(() => import('../../props/showcase/general/Coaster'), 'Coaster') },
      { id: 'usb-hub', name: 'USB Hub', color: '#44ff88', component: lz(() => import('../../props/showcase/general/USBHub'), 'USBHub') },
      { id: 'wireless-charger', name: 'Wireless Charger', color: '#44aaff', component: lz(() => import('../../props/showcase/general/WirelessCharger'), 'WirelessCharger') },
      { id: 'nameplate', name: 'Nameplate', color: '#cc9933', component: lz(() => import('../../props/showcase/general/Nameplate'), 'Nameplate') },
      { id: 'tissue-box', name: 'Tissue Box', color: '#88ccff', component: lz(() => import('../../props/showcase/general/TissueBox'), 'TissueBox') },
      { id: 'hand-sanitizer', name: 'Hand Sanitizer', color: '#44ccff', component: lz(() => import('../../props/showcase/general/HandSanitizer'), 'HandSanitizer') },
      { id: 'desk-mirror', name: 'Desk Mirror', color: '#cc9944', component: lz(() => import('../../props/showcase/general/DeskMirror'), 'DeskMirror') },
      { id: 'mini-fridge', name: 'Mini Fridge', color: '#44ccff', component: lz(() => import('../../props/showcase/general/MiniFridge'), 'MiniFridge') },
    ],
  },
  {
    id: 'office', name: 'Office & Productivity', icon: '🏢',
    props: [
      { id: 'desk-lamp', name: 'Desk Lamp', color: '#ffcc44', component: lz(() => import('../../props/showcase/office/DeskLamp'), 'DeskLamp') },
      { id: 'monitor', name: 'Monitor', color: '#4488ff', component: lz(() => import('../../props/showcase/office/Monitor'), 'Monitor') },
      { id: 'keyboard', name: 'Keyboard', color: '#ff44ff', component: lz(() => import('../../props/showcase/office/Keyboard'), 'Keyboard') },
      { id: 'coffee-mug', name: 'Coffee Mug', color: '#ff6644', component: lz(() => import('../../props/showcase/office/CoffeeMug'), 'CoffeeMug') },
      { id: 'printer', name: 'Printer', color: '#88dd88', component: lz(() => import('../../props/showcase/office/Printer'), 'Printer') },
      { id: 'filing-cabinet', name: 'Filing Cabinet', color: '#7788aa', component: lz(() => import('../../props/showcase/office/FilingCabinet'), 'FilingCabinet') },
      { id: 'bookshelf', name: 'Bookshelf', color: '#aa8844', component: lz(() => import('../../props/showcase/office/Bookshelf'), 'Bookshelf') },
      { id: 'stapler', name: 'Stapler', color: '#ff2222', component: lz(() => import('../../props/showcase/office/Stapler'), 'Stapler') },
      { id: 'desk-clock', name: 'Desk Clock', color: '#cc8833', component: lz(() => import('../../props/showcase/office/DeskClock'), 'DeskClock') },
      { id: 'headphones', name: 'Headphones', color: '#44ffaa', component: lz(() => import('../../props/showcase/office/Headphones'), 'Headphones') },
      { id: 'water-bottle', name: 'Water Bottle', color: '#4488dd', component: lz(() => import('../../props/showcase/office/WaterBottle'), 'WaterBottle') },
      { id: 'hole-puncher', name: 'Hole Puncher', color: '#444455', component: lz(() => import('../../props/showcase/office/HolePuncher'), 'HolePuncher') },
      { id: 'label-maker', name: 'Label Maker', color: '#4488dd', component: lz(() => import('../../props/showcase/office/LabelMaker'), 'LabelMaker') },
      { id: 'paper-clips-holder', name: 'Paper Clips Holder', color: '#ff44ff', component: lz(() => import('../../props/showcase/office/PaperClipsHolder'), 'PaperClipsHolder') },
      { id: 'rubber-stamps', name: 'Rubber Stamps', color: '#ff4444', component: lz(() => import('../../props/showcase/office/RubberStamps'), 'RubberStamps') },
      { id: 'sticky-note-dispenser', name: 'Sticky Note Dispenser', color: '#ffee44', component: lz(() => import('../../props/showcase/office/StickyNoteDispenser'), 'StickyNoteDispenser') },
      { id: 'business-card-holder', name: 'Business Card Holder', color: '#333344', component: lz(() => import('../../props/showcase/office/BusinessCardHolder'), 'BusinessCardHolder') },
      { id: 'document-tray', name: 'Document Tray', color: '#666677', component: lz(() => import('../../props/showcase/office/DocumentTray'), 'DocumentTray') },
      { id: 'scientific-calculator', name: 'Scientific Calculator', color: '#88bbaa', component: lz(() => import('../../props/showcase/office/ScientificCalculator'), 'ScientificCalculator') },
      { id: 'envelope-opener', name: 'Envelope Opener', color: '#ccbb88', component: lz(() => import('../../props/showcase/office/EnvelopeOpener'), 'EnvelopeOpener') },
      { id: 'magnifying-lamp', name: 'Magnifying Lamp', color: '#ffffcc', component: lz(() => import('../../props/showcase/office/MagnifyingLamp'), 'MagnifyingLamp') },
      { id: 'desk-phone', name: 'Desk Phone', color: '#44ccaa', component: lz(() => import('../../props/showcase/office/DeskPhone'), 'DeskPhone') },
      { id: 'conference-speaker', name: 'Conference Speaker', color: '#44ff88', component: lz(() => import('../../props/showcase/office/ConferenceSpeakerphone'), 'ConferenceSpeakerphone') },
      { id: 'projector', name: 'Projector', color: '#ffffcc', component: lz(() => import('../../props/showcase/office/Projector'), 'Projector') },
      { id: 'laser-pointer', name: 'Laser Pointer', color: '#ff2222', component: lz(() => import('../../props/showcase/office/PresentationPointer'), 'PresentationPointer') },
      { id: 'flipchart-stand', name: 'Flipchart Stand', color: '#ffffff', component: lz(() => import('../../props/showcase/office/FlipchartStand'), 'FlipchartStand') },
      { id: 'badge-holder', name: 'Badge Holder', color: '#4488ff', component: lz(() => import('../../props/showcase/office/BadgeHolder'), 'BadgeHolder') },
      { id: 'time-clock', name: 'Time Clock', color: '#44cc44', component: lz(() => import('../../props/showcase/office/TimeClock'), 'TimeClock') },
      { id: 'paper-trimmer', name: 'Paper Trimmer', color: '#ccccdd', component: lz(() => import('../../props/showcase/office/PaperTrimmer'), 'PaperTrimmer') },
      { id: 'binding-machine', name: 'Binding Machine', color: '#555566', component: lz(() => import('../../props/showcase/office/BindingMachine'), 'BindingMachine') },
      { id: 'laminator', name: 'Laminator', color: '#44ff44', component: lz(() => import('../../props/showcase/office/Laminator'), 'Laminator') },
    ],
  },
  {
    id: 'tech', name: 'Tech & Developer', icon: '💻',
    props: [
      { id: 'raspberry-pi', name: 'Raspberry Pi', color: '#228833', component: lz(() => import('../../props/showcase/tech/RaspberryPi'), 'RaspberryPi') },
      { id: 'router', name: 'Router', color: '#44ff66', component: lz(() => import('../../props/showcase/tech/Router'), 'Router') },
      { id: 'usb-drive', name: 'USB Drive', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/USBDrive'), 'USBDrive') },
      { id: 'mech-keyboard', name: 'Mech Keyboard', color: '#ff44ff', component: lz(() => import('../../props/showcase/tech/MechKeyboard'), 'MechKeyboard') },
      { id: 'hard-drive', name: 'Hard Drive', color: '#aaaacc', component: lz(() => import('../../props/showcase/tech/HardDrive'), 'HardDrive') },
      { id: 'vr-headset', name: 'VR Headset', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/VRHeadset'), 'VRHeadset') },
      { id: 'circuit-board', name: 'Circuit Board', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/CircuitBoard'), 'CircuitBoard') },
      { id: 'monitor-stand', name: 'Monitor Stand', color: '#666688', component: lz(() => import('../../props/showcase/tech/MonitorStand'), 'MonitorStand') },
      { id: 'power-strip', name: 'Power Strip', color: '#ff4444', component: lz(() => import('../../props/showcase/tech/PowerStrip'), 'PowerStrip') },
      { id: 'soldering-iron', name: 'Soldering Iron', color: '#ff8844', component: lz(() => import('../../props/showcase/tech/SolderingIron'), 'SolderingIron') },
      { id: 'ethernet-spool', name: 'Ethernet Spool', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/EthernetCableSpool'), 'EthernetCableSpool') },
      { id: 'network-switch', name: 'Network Switch', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/NetworkSwitch'), 'NetworkSwitch') },
      { id: 'modem', name: 'Modem', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/Modem'), 'Modem') },
      { id: 'wifi-extender', name: 'WiFi Extender', color: '#44aaff', component: lz(() => import('../../props/showcase/tech/WiFiExtender'), 'WiFiExtender') },
      { id: 'bt-speaker', name: 'BT Speaker', color: '#ff4488', component: lz(() => import('../../props/showcase/tech/BluetoothSpeaker'), 'BluetoothSpeaker') },
      { id: 'sd-card-reader', name: 'SD Card Reader', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/SDCardReader'), 'SDCardReader') },
      { id: 'external-ssd', name: 'External SSD', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/ExternalSSD'), 'ExternalSSD') },
      { id: 'nas-drive', name: 'NAS Drive', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/NASDrive'), 'NASDrive') },
      { id: 'backup-battery', name: 'Backup Battery', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/BackupBattery'), 'BackupBattery') },
      { id: 'cooling-fan', name: 'Cooling Fan', color: '#555577', component: lz(() => import('../../props/showcase/tech/CoolingFan'), 'CoolingFan') },
      { id: 'thermal-paste', name: 'Thermal Paste', color: '#888899', component: lz(() => import('../../props/showcase/tech/ThermalPasteTube'), 'ThermalPasteTube') },
      { id: 'esd-strap', name: 'ESD Strap', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/AntiStaticWristStrap'), 'AntiStaticWristStrap') },
      { id: 'cable-tester', name: 'Cable Tester', color: '#ffcc44', component: lz(() => import('../../props/showcase/tech/CableTester'), 'CableTester') },
      { id: 'multimeter', name: 'Multimeter', color: '#ffcc22', component: lz(() => import('../../props/showcase/tech/Multimeter'), 'Multimeter') },
      { id: 'oscilloscope', name: 'Oscilloscope', color: '#44ff44', component: lz(() => import('../../props/showcase/tech/Oscilloscope'), 'Oscilloscope') },
      { id: 'logic-analyzer', name: 'Logic Analyzer', color: '#44ffaa', component: lz(() => import('../../props/showcase/tech/LogicAnalyzer'), 'LogicAnalyzer') },
      { id: 'fpga-board', name: 'FPGA Board', color: '#225522', component: lz(() => import('../../props/showcase/tech/FPGABoard'), 'FPGABoard') },
      { id: 'mcu-kit', name: 'MCU Kit', color: '#ff4444', component: lz(() => import('../../props/showcase/tech/MicrocontrollerKit'), 'MicrocontrollerKit') },
      { id: 'led-matrix', name: 'LED Matrix', color: '#ff2222', component: lz(() => import('../../props/showcase/tech/LEDMatrixDisplay'), 'LEDMatrixDisplay') },
      { id: 'servo-motors', name: 'Servo Motors', color: '#4488ff', component: lz(() => import('../../props/showcase/tech/ServoMotors'), 'ServoMotors') },
    ],
  },
  {
    id: 'creative', name: 'Creative & Art', icon: '🎭',
    props: [
      { id: 'easel', name: 'Easel', color: '#ff4466', component: lz(() => import('../../props/showcase/creative/Easel'), 'Easel') },
      { id: 'paint-palette', name: 'Paint Palette', color: '#ff8833', component: lz(() => import('../../props/showcase/creative/PaintPalette'), 'PaintPalette') },
      { id: 'camera', name: 'Camera', color: '#444466', component: lz(() => import('../../props/showcase/creative/Camera'), 'Camera') },
      { id: 'pen-tablet', name: 'Pen Tablet', color: '#4488ff', component: lz(() => import('../../props/showcase/creative/PenTablet'), 'PenTablet') },
      { id: 'sketchbook', name: 'Sketchbook', color: '#884422', component: lz(() => import('../../props/showcase/creative/Sketchbook'), 'Sketchbook') },
      { id: 'ring-light', name: 'Ring Light', color: '#ffffaa', component: lz(() => import('../../props/showcase/creative/RingLight'), 'RingLight') },
      { id: 'color-wheel', name: 'Color Wheel', color: '#ff00ff', component: lz(() => import('../../props/showcase/creative/ColorWheel'), 'ColorWheel') },
      { id: 'scissors', name: 'Scissors', color: '#ff4444', component: lz(() => import('../../props/showcase/creative/Scissors'), 'Scissors') },
      { id: 'sticky-notes', name: 'Sticky Notes', color: '#ffee44', component: lz(() => import('../../props/showcase/creative/StickyNotes'), 'StickyNotes') },
      { id: 'tripod', name: 'Tripod', color: '#666688', component: lz(() => import('../../props/showcase/creative/Tripod'), 'Tripod') },
      { id: 'spray-paint', name: 'Spray Paint', color: '#ff4488', component: lz(() => import('../../props/showcase/creative/SprayPaintCan'), 'SprayPaintCan') },
      { id: 'airbrush', name: 'Airbrush', color: '#aaaacc', component: lz(() => import('../../props/showcase/creative/AirbrushKit'), 'AirbrushKit') },
      { id: 'charcoal-sticks', name: 'Charcoal Sticks', color: '#222222', component: lz(() => import('../../props/showcase/creative/CharcoalSticks'), 'CharcoalSticks') },
      { id: 'oil-pastels', name: 'Oil Pastels', color: '#ff8833', component: lz(() => import('../../props/showcase/creative/OilPastels'), 'OilPastels') },
      { id: 'watercolor-set', name: 'Watercolor Set', color: '#ff4444', component: lz(() => import('../../props/showcase/creative/WatercolorSet'), 'WatercolorSet') },
      { id: 'canvas-stretcher', name: 'Canvas Stretcher', color: '#aa8844', component: lz(() => import('../../props/showcase/creative/CanvasStretcher'), 'CanvasStretcher') },
      { id: 'gesso-jar', name: 'Gesso Jar', color: '#4488ff', component: lz(() => import('../../props/showcase/creative/GessoJar'), 'GessoJar') },
      { id: 'palette-knife', name: 'Palette Knife', color: '#ccccdd', component: lz(() => import('../../props/showcase/creative/PaletteKnife'), 'PaletteKnife') },
      { id: 'brush-cleaner', name: 'Brush Cleaner', color: '#8899bb', component: lz(() => import('../../props/showcase/creative/BrushCleanerJar'), 'BrushCleanerJar') },
      { id: 'masking-tape', name: 'Masking Tape', color: '#eedd88', component: lz(() => import('../../props/showcase/creative/MaskingTape'), 'MaskingTape') },
      { id: 'cutting-mat', name: 'Cutting Mat', color: '#228844', component: lz(() => import('../../props/showcase/creative/CuttingMat'), 'CuttingMat') },
      { id: 'x-acto-knife', name: 'X-Acto Knife', color: '#ccccdd', component: lz(() => import('../../props/showcase/creative/XActoKnife'), 'XActoKnife') },
      { id: 'kneaded-eraser', name: 'Kneaded Eraser', color: '#bbbbcc', component: lz(() => import('../../props/showcase/creative/KneadedEraser'), 'KneadedEraser') },
      { id: 'fixative-spray', name: 'Fixative Spray', color: '#4488ff', component: lz(() => import('../../props/showcase/creative/FixativeSpray'), 'FixativeSpray') },
      { id: 'portfolio-case', name: 'Portfolio Case', color: '#333355', component: lz(() => import('../../props/showcase/creative/PortfolioCase'), 'PortfolioCase') },
      { id: 'lightbox', name: 'Lightbox', color: '#ffffff', component: lz(() => import('../../props/showcase/creative/Lightbox'), 'Lightbox') },
      { id: 'color-swatches', name: 'Color Swatches', color: '#ff44aa', component: lz(() => import('../../props/showcase/creative/ColorSwatches'), 'ColorSwatches') },
      { id: 'ink-bottles', name: 'Ink Bottles', color: '#ff2244', component: lz(() => import('../../props/showcase/creative/InkBottles'), 'InkBottles') },
      { id: 'calligraphy-pens', name: 'Calligraphy Pens', color: '#884422', component: lz(() => import('../../props/showcase/creative/CalligraphyPens'), 'CalligraphyPens') },
      { id: 'clay-tools', name: 'Clay Tools', color: '#bb9966', component: lz(() => import('../../props/showcase/creative/ClaySculptingTools'), 'ClaySculptingTools') },
    ],
  },
  {
    id: 'gaming', name: 'Gaming & Entertainment', icon: '🎮',
    props: [
      { id: 'game-controller', name: 'Game Controller', color: '#4488ff', component: lz(() => import('../../props/showcase/gaming/GameController'), 'GameController') },
      { id: 'gaming-chair', name: 'Gaming Chair', color: '#ff2244', component: lz(() => import('../../props/showcase/gaming/GamingChair'), 'GamingChair') },
      { id: 'arcade-stick', name: 'Arcade Stick', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/ArcadeStick'), 'ArcadeStick') },
      { id: 'figurine', name: 'Figurine', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/Figurine'), 'Figurine') },
      { id: 'dice', name: 'Dice', color: '#4488ff', component: lz(() => import('../../props/showcase/gaming/Dice'), 'Dice') },
      { id: 'rgb-strip', name: 'RGB Strip', color: '#ff00ff', component: lz(() => import('../../props/showcase/gaming/RGBStrip'), 'RGBStrip') },
      { id: 'headset-stand', name: 'Headset Stand', color: '#ff44ff', component: lz(() => import('../../props/showcase/gaming/HeadsetStand'), 'HeadsetStand') },
      { id: 'energy-drink', name: 'Energy Drink', color: '#44ff44', component: lz(() => import('../../props/showcase/gaming/EnergyDrink'), 'EnergyDrink') },
      { id: 'gaming-mouse-pad', name: 'Gaming Mouse Pad', color: '#ff00ff', component: lz(() => import('../../props/showcase/gaming/GamingMousePad'), 'GamingMousePad') },
      { id: 'poster', name: 'Poster', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/Poster'), 'Poster') },
      { id: 'game-cartridge', name: 'Game Cartridge', color: '#ffcc44', component: lz(() => import('../../props/showcase/gaming/GameCartridge'), 'GameCartridge') },
      { id: 'memory-card', name: 'Memory Card', color: '#44ff44', component: lz(() => import('../../props/showcase/gaming/MemoryCard'), 'MemoryCard') },
      { id: 'controller-grip', name: 'Controller Grip', color: '#44ff44', component: lz(() => import('../../props/showcase/gaming/ControllerGrip'), 'ControllerGrip') },
      { id: 'thumbstick-caps', name: 'Thumbstick Caps', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/ThumbstickCaps'), 'ThumbstickCaps') },
      { id: 'gaming-keyboard', name: 'Gaming Keyboard', color: '#ff44ff', component: lz(() => import('../../props/showcase/gaming/GamingKeyboard'), 'GamingKeyboard') },
      { id: 'mouse-bungee', name: 'Mouse Bungee', color: '#333344', component: lz(() => import('../../props/showcase/gaming/MouseBungee'), 'MouseBungee') },
      { id: 'wrist-rest', name: 'Wrist Rest', color: '#ff44ff', component: lz(() => import('../../props/showcase/gaming/WristRest'), 'WristRest') },
      { id: 'monitor-arm', name: 'Monitor Arm', color: '#555566', component: lz(() => import('../../props/showcase/gaming/MonitorArm'), 'MonitorArm') },
      { id: 'cable-sleeve', name: 'Cable Sleeve', color: '#ff00ff', component: lz(() => import('../../props/showcase/gaming/CableSleeve'), 'CableSleeve') },
      { id: 'stream-mic', name: 'Stream Mic', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/StreamingMicrophone'), 'StreamingMicrophone') },
      { id: 'green-screen', name: 'Green Screen', color: '#22cc44', component: lz(() => import('../../props/showcase/gaming/GreenScreen'), 'GreenScreen') },
      { id: 'key-light', name: 'Key Light', color: '#ffffee', component: lz(() => import('../../props/showcase/gaming/KeyLight'), 'KeyLight') },
      { id: 'capture-card', name: 'Capture Card', color: '#4488ff', component: lz(() => import('../../props/showcase/gaming/CaptureCard'), 'CaptureCard') },
      { id: 'console-stand', name: 'Console Stand', color: '#4488ff', component: lz(() => import('../../props/showcase/gaming/ConsoleStand'), 'ConsoleStand') },
      { id: 'game-cases', name: 'Game Cases', color: '#4488ff', component: lz(() => import('../../props/showcase/gaming/GameCaseStorage'), 'GameCaseStorage') },
      { id: 'amiibo-figure', name: 'Amiibo Figure', color: '#ffcc44', component: lz(() => import('../../props/showcase/gaming/AmiiboFigure'), 'AmiiboFigure') },
      { id: 'pop-figure', name: 'Pop Figure', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/PopFigure'), 'PopFigure') },
      { id: 'esports-trophy', name: 'Esports Trophy', color: '#ffdd44', component: lz(() => import('../../props/showcase/gaming/EsportsTrophy'), 'EsportsTrophy') },
      { id: 'lan-cable', name: 'LAN Cable', color: '#ffcc44', component: lz(() => import('../../props/showcase/gaming/LANCable'), 'LANCable') },
      { id: 'chair-footrest', name: 'Chair Footrest', color: '#ff4444', component: lz(() => import('../../props/showcase/gaming/GamingChairFootrest'), 'GamingChairFootrest') },
    ],
  },
  {
    id: 'science', name: 'Science & Lab', icon: '🔬',
    props: [
      { id: 'microscope', name: 'Microscope', color: '#ffffdd', component: lz(() => import('../../props/showcase/science/Microscope'), 'Microscope') },
      { id: 'test-tubes', name: 'Test Tubes', color: '#ff4466', component: lz(() => import('../../props/showcase/science/TestTubes'), 'TestTubes') },
      { id: 'beaker', name: 'Beaker', color: '#44ddaa', component: lz(() => import('../../props/showcase/science/Beaker'), 'Beaker') },
      { id: 'bunsen-burner', name: 'Bunsen Burner', color: '#4488ff', component: lz(() => import('../../props/showcase/science/BunsenBurner'), 'BunsenBurner') },
      { id: 'molecular-model', name: 'Molecular Model', color: '#ff4444', component: lz(() => import('../../props/showcase/science/MolecularModel'), 'MolecularModel') },
      { id: 'telescope', name: 'Telescope', color: '#ddddee', component: lz(() => import('../../props/showcase/science/Telescope'), 'Telescope') },
      { id: 'magnifying-glass', name: 'Magnifying Glass', color: '#cc8833', component: lz(() => import('../../props/showcase/science/MagnifyingGlass'), 'MagnifyingGlass') },
      { id: 'safety-goggles', name: 'Safety Goggles', color: '#4488ff', component: lz(() => import('../../props/showcase/science/SafetyGoggles'), 'SafetyGoggles') },
      { id: 'petri-dish', name: 'Petri Dish', color: '#44aa44', component: lz(() => import('../../props/showcase/science/PetriDish'), 'PetriDish') },
      { id: 'thermometer', name: 'Thermometer', color: '#ff2244', component: lz(() => import('../../props/showcase/science/Thermometer'), 'Thermometer') },
      { id: 'burner-tripod', name: 'Burner Tripod', color: '#888899', component: lz(() => import('../../props/showcase/science/BunsenBurnerTripod'), 'BunsenBurnerTripod') },
      { id: 'crucible-tongs', name: 'Crucible Tongs', color: '#888899', component: lz(() => import('../../props/showcase/science/CrucibleTongs'), 'CrucibleTongs') },
      { id: 'stirring-rod', name: 'Stirring Rod', color: '#ccddee', component: lz(() => import('../../props/showcase/science/StirringRod'), 'StirringRod') },
      { id: 'dropper-bottle', name: 'Dropper Bottle', color: '#ff8844', component: lz(() => import('../../props/showcase/science/DropperBottle'), 'DropperBottle') },
      { id: 'pipette-stand', name: 'Pipette Stand', color: '#4488ff', component: lz(() => import('../../props/showcase/science/PipetteStand'), 'PipetteStand') },
      { id: 'lab-notebook', name: 'Lab Notebook', color: '#222266', component: lz(() => import('../../props/showcase/science/LabNotebook'), 'LabNotebook') },
      { id: 'safety-shower', name: 'Safety Shower', color: '#ffcc44', component: lz(() => import('../../props/showcase/science/SafetyShower'), 'SafetyShower') },
      { id: 'fume-hood', name: 'Fume Hood', color: '#44ff44', component: lz(() => import('../../props/showcase/science/FumeHoodModel'), 'FumeHoodModel') },
      { id: 'autoclave', name: 'Autoclave', color: '#ff4444', component: lz(() => import('../../props/showcase/science/Autoclave'), 'Autoclave') },
      { id: 'centrifuge', name: 'Centrifuge', color: '#4488ff', component: lz(() => import('../../props/showcase/science/Centrifuge'), 'Centrifuge') },
      { id: 'ph-meter', name: 'pH Meter', color: '#44ccaa', component: lz(() => import('../../props/showcase/science/PHMeter'), 'PHMeter') },
      { id: 'litmus-paper', name: 'Litmus Paper', color: '#ff8844', component: lz(() => import('../../props/showcase/science/LitmusPaper'), 'LitmusPaper') },
      { id: 'graduated-cylinder', name: 'Graduated Cylinder', color: '#4488ff', component: lz(() => import('../../props/showcase/science/GraduatedCylinder'), 'GraduatedCylinder') },
      { id: 'conical-flask', name: 'Conical Flask', color: '#88ddaa', component: lz(() => import('../../props/showcase/science/ConicalFlask'), 'ConicalFlask') },
      { id: 'mortar-pestle', name: 'Mortar & Pestle', color: '#aaaacc', component: lz(() => import('../../props/showcase/science/MortarAndPestle'), 'MortarAndPestle') },
      { id: 'lab-timer', name: 'Lab Timer', color: '#ff4444', component: lz(() => import('../../props/showcase/science/LabTimer'), 'LabTimer') },
      { id: 'specimen-jar', name: 'Specimen Jar', color: '#ddcc88', component: lz(() => import('../../props/showcase/science/SpecimenJar'), 'SpecimenJar') },
      { id: 'microscope-slides', name: 'Microscope Slides', color: '#ccddee', component: lz(() => import('../../props/showcase/science/MicroscopeSlides'), 'MicroscopeSlides') },
      { id: 'cover-slips', name: 'Cover Slips', color: '#eeeeff', component: lz(() => import('../../props/showcase/science/CoverSlips'), 'CoverSlips') },
      { id: 'lab-apron', name: 'Lab Apron', color: '#ffffff', component: lz(() => import('../../props/showcase/science/LabApron'), 'LabApron') },
    ],
  },
  {
    id: 'workshop', name: 'Workshop & Tools', icon: '🔧',
    props: [
      { id: 'hammer', name: 'Hammer', color: '#aa7744', component: lz(() => import('../../props/showcase/workshop/Hammer'), 'Hammer') },
      { id: 'drill', name: 'Drill', color: '#22aa44', component: lz(() => import('../../props/showcase/workshop/Drill'), 'Drill') },
      { id: 'toolbox', name: 'Toolbox', color: '#cc2222', component: lz(() => import('../../props/showcase/workshop/Toolbox'), 'Toolbox') },
      { id: 'measuring-tape', name: 'Measuring Tape', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/MeasuringTape'), 'MeasuringTape') },
      { id: 'wrench', name: 'Wrench', color: '#aaaacc', component: lz(() => import('../../props/showcase/workshop/Wrench'), 'Wrench') },
      { id: 'paint-can', name: 'Paint Can', color: '#4488ff', component: lz(() => import('../../props/showcase/workshop/PaintCan'), 'PaintCan') },
      { id: 'workbench', name: 'Workbench', color: '#aa8844', component: lz(() => import('../../props/showcase/workshop/Workbench'), 'Workbench') },
      { id: 'safety-helmet', name: 'Safety Helmet', color: '#ffcc00', component: lz(() => import('../../props/showcase/workshop/SafetyHelmet'), 'SafetyHelmet') },
      { id: 'screwdriver', name: 'Screwdriver', color: '#ff6622', component: lz(() => import('../../props/showcase/workshop/Screwdriver'), 'Screwdriver') },
      { id: 'wood-planks', name: 'Wood Planks', color: '#bb8844', component: lz(() => import('../../props/showcase/workshop/WoodPlanks'), 'WoodPlanks') },
      { id: 'chisel-set', name: 'Chisel Set', color: '#bb9966', component: lz(() => import('../../props/showcase/workshop/ChiselSet'), 'ChiselSet') },
      { id: 'wood-plane', name: 'Wood Plane', color: '#bb9955', component: lz(() => import('../../props/showcase/workshop/WoodPlane'), 'WoodPlane') },
      { id: 'c-clamp', name: 'C-Clamp', color: '#ff6622', component: lz(() => import('../../props/showcase/workshop/CClamp'), 'CClamp') },
      { id: 'angle-grinder', name: 'Angle Grinder', color: '#44aa44', component: lz(() => import('../../props/showcase/workshop/AngleGrinder'), 'AngleGrinder') },
      { id: 'jigsaw', name: 'Jigsaw', color: '#ff8822', component: lz(() => import('../../props/showcase/workshop/Jigsaw'), 'Jigsaw') },
      { id: 'circular-saw', name: 'Circular Saw', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/CircularSaw'), 'CircularSaw') },
      { id: 'wood-router', name: 'Wood Router', color: '#44aa44', component: lz(() => import('../../props/showcase/workshop/WoodRouter'), 'WoodRouter') },
      { id: 'orbital-sander', name: 'Orbital Sander', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/OrbitalSander'), 'OrbitalSander') },
      { id: 'nail-gun', name: 'Nail Gun', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/NailGun'), 'NailGun') },
      { id: 'staple-gun', name: 'Staple Gun', color: '#888899', component: lz(() => import('../../props/showcase/workshop/StapleGun'), 'StapleGun') },
      { id: 'wire-cutters', name: 'Wire Cutters', color: '#ff4444', component: lz(() => import('../../props/showcase/workshop/WireCutters'), 'WireCutters') },
      { id: 'needle-nose-pliers', name: 'Needle Nose Pliers', color: '#ff4444', component: lz(() => import('../../props/showcase/workshop/NeedleNosePliers'), 'NeedleNosePliers') },
      { id: 'allen-key-set', name: 'Allen Key Set', color: '#888899', component: lz(() => import('../../props/showcase/workshop/AllenKeySet'), 'AllenKeySet') },
      { id: 'socket-wrench-set', name: 'Socket Wrench Set', color: '#ff4444', component: lz(() => import('../../props/showcase/workshop/SocketWrenchSet'), 'SocketWrenchSet') },
      { id: 'torque-wrench', name: 'Torque Wrench', color: '#aaaacc', component: lz(() => import('../../props/showcase/workshop/TorqueWrench'), 'TorqueWrench') },
      { id: 'pipe-wrench', name: 'Pipe Wrench', color: '#ff4444', component: lz(() => import('../../props/showcase/workshop/PipeWrench'), 'PipeWrench') },
      { id: 'adjustable-spanner', name: 'Adjustable Spanner', color: '#aaaacc', component: lz(() => import('../../props/showcase/workshop/AdjustableSpanner'), 'AdjustableSpanner') },
      { id: 'utility-knife', name: 'Utility Knife', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/UtilityKnife'), 'UtilityKnife') },
      { id: 'tape-measure-xl', name: 'Tape Measure XL', color: '#ffcc22', component: lz(() => import('../../props/showcase/workshop/LargeTapeMeasure'), 'LargeTapeMeasure') },
      { id: 'work-light', name: 'Work Light', color: '#ffffcc', component: lz(() => import('../../props/showcase/workshop/WorkLight'), 'WorkLight') },
    ],
  },
]

// Flat list for backward compatibility
export const showcaseProps: ShowcaseProp[] = showcaseCategories.flatMap(c => c.props)
